language: ruby
script: "bundle exec rake test:units TEST=test/remote/gateways/remote_openpay_test.rb --trace"
sudo: false

rvm:
- "2.2"

gemfile:
- Gemfile.rails42
- Gemfile.rails41

notifications:
  email:
  - developers@openpay.mx
