language: ruby
script: "bundle exec rake test:units TEST=test/remote/gateways/remote_openpay_test.rb --trace"
sudo: false

rvm:
- "2.4"
- "2.3"
- "2.2"

gemfile:
- Gemfile.rails40
- Gemfile.rails41
- Gemfile.rails42

notifications:
  email:
  - developers@openpay.mx
